### PR TITLE
planning added

### PR DESCRIPTION
**Pull request by angelasandom**

### CODE REVIEW

**Review by nc-mitch-wyatt — COMMENTED** [review]
I like that you've got your colour scheme included and prepared 🎨 

This plan isn't too bad but it's not telling me much about how a user will navigate around your app. It's worthwhile thinking about what frontend routes you want to have, the API calls you might need. When accessing a filtered list of a particular topic, how will the URL change to reflect that. These are essential to be part of the plan but it's worth thinking about ahead of time 

Let me know if you have any questions about anything I've mentioned! 😄

**Comment by nc-mitch-wyatt** [comment]
As an example for the above:

- How does a user get from the home page to viewing a particular article they want to read?
- After reading an article how does a user get to read the comments
- After reading the comments, how can a user post a comment of their own

**Comment by angelasandom** [comment]
Thank you Mitch. I guess with onClick handleCLick the article card should link you to the article by its id, so from /articles to /api/articles/:article_id. From an article if you want to see comments you need a button onclick to display and link to /api/articles/:article_id/comments. I cant add the path to post a comment since I didnt get there in BE. Am I right?

**Comment by angelasandom** [comment]
Thank you Mitch, I commented on the code but I think you cant see it.
 I guess with onClick handleCLick the article card should link you to the
article by its id, so from /articles to /api/articles/:article_id. From an
article if you want to see comments you need a button onclick to display
and link to /api/articles/:article_id/comments. I cant add the path to post
a comment since I didnt get there in BE. Am I right?

**Pull request merged**
